# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Osoitetyokalu
                                 A QGIS plugin
 Osoitetyokalu
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-07-19
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sitowise
        email                : support@sitowise.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


import pandas as pd
import os.path
from ctypes import pointer
from qgis.core import QgsMessageLog
import logging
formatter = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
logfilename=os.path.join(os.path.dirname(__file__), 'logs/log.txt')
logfilename=r'C:\Projects\PTP\PTP-1360\osoitetyokalu\logs\log.txt'
logging.basicConfig(filename=logfilename, level=logging.DEBUG, format=formatter)

from sympy import Point
from .dialogs.ShowCoordinates_dialog import ShowCoordinates_dialog
from .dialogs.PopUp_dialog import PopUp_dialog
from .dialogs.Ajoradat_dialog import Ajoradat_dialog
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.gui import QgsMapToolEmitPoint
from qgis.gui import QgsMapTool, QgsMapCanvasAnnotationItem
from qgis.core import QgsField, QgsFeature, QgsVectorLayer, QgsProject, QgsCoordinateReferenceSystem, QgsGeometry, QgsPointXY
from qgis.core import  QgsAnnotationLayer, QgsAnnotationPointTextItem, QgsTextAnnotation, QgsTextDocument, QgsPoint
from qgis.gui import QgsMessageBar

from PyQt5.QtGui import QTextDocument
from PyQt5.QtCore import QSizeF,QPoint

from requests import get
import json

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Osoitetyokalu_dialog import OsoitetyokaluDialog



class Osoitetyokalu:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Osoitetyokalu_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Osoitetyokalu')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.my_crs = QgsCoordinateReferenceSystem.fromEpsgId(3067)


        #Setting up canvas to click
        
        
        



    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Osoitetyokalu', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Osoitetyokalu/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Tieosoite'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

        self.add_action(
            icon_path,
            text=self.tr(u'Popup-ikkuna'),
            callback=self.popup,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False)

        self.add_action(
            icon_path,
            text=self.tr(u'Tieosoite (Alku- ja loppupiste)'),
            callback=self.two_points,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False)
#

   # def show_coordinates(self):
   #     canvas_clicked = PrintClickedPoint( self.iface.mapCanvas() )
#
   #     self.iface.mapCanvas().setMapTool( canvas_clicked )

        
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Osoitetyokalu'),
                action)
            self.iface.removeToolBarIcon(action)


    def close_popup(self):
            dlg = PopUp_dialog
            dlg.close()

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
        dlg = ShowCoordinates_dialog()
        dlg.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)


        def display_point(pointTool):
            try:

                #click on canvas returns coordinates
                print(pointTool.x(), pointTool.y())
                point_x = str(pointTool.x())
                point_y = str(pointTool.y())
                dlg.CoordLineEdit.setText(f'{point_x}, {point_y}')

                #get new coordinates and address from VKM
                vkm_url='https://avoinapi.vaylapilvi.fi/viitekehysmuunnin/'
                try:
                    road_address, vkm_error, point_x, point_y, _, _, _ = self.vkm_request_road_address(vkm_url=vkm_url, point_x=point_x, point_y=point_y)
                except:
                    road_address, vkm_error = self.vkm_request_road_address(vkm_url=vkm_url, point_x=point_x, point_y=point_y)

                if vkm_error == True:
                    dlg.AddrLineEdit.setText(road_address)
                
                else:
                    dlg.AddrLineEdit.setText(road_address)
                    #draws a point with clicked coordinates
                    self.add_point(road_address=road_address, point_x=point_x, point_y=point_y)
                    
                    #adding an annotation with road address to the latest point
                    self.add_annotation(road_address=road_address, point_x=point_x, point_y=point_y)
                    
            except AttributeError:
                pass


        #self.iface.newProject()

        #CRS when the ShowCoordinates-tool is opened
        QgsProject.instance().setCrs(self.my_crs)

        canvas = self.iface.mapCanvas()
        pointTool = QgsMapToolEmitPoint(canvas)
        pointTool.canvasClicked.connect(display_point)
        canvas.setMapTool(pointTool)
        display_point(pointTool)

        # show the dialog
        dlg.show()
        # Run the dialog event loop
        result = dlg.exec_()
        # See if OK was pressed
        if result:
            
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass


    def popup(self):
        if self.first_start == True:
            self.first_start = False
        dlg = PopUp_dialog()
        dlg.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)


        def display_popup(pointTool):
            try:
                QgsProject.instance().setCrs(self.my_crs)
                #canvas = self.iface.mapCanvas()

                point_x = str(pointTool.x())
                point_y = str(pointTool.y())
                #get new coordinates and address from VKM
                vkm_url = 'https://avoinapi.vaylapilvi.fi/viitekehysmuunnin/'
                response = get(vkm_url + f'muunna?x={point_x}&y={point_y}&palautusarvot=1,2,3,4,5,6&vaylan_luonne=0')

                while response.status_code !=200: #retry
                    logging.info('retrying')
                    response = get(vkm_url + f'muunna?x={point_x}&y={point_y}&palautusarvot=1,2,3,4,5,6&vaylan_luonne=0')

                vkm_error = False
                vkm_data = json.loads(response.content)
                for vkm_feature in vkm_data['features']:
                    print(vkm_feature)
                    if 'virheet' in vkm_feature['properties']:
                        road_address = vkm_feature['properties']['virheet']
                        vkm_error = True
                        
                    else:
                        try:
                            #getting road coordinates and road address that are nearest to the mouse click
                            #print(vkm_feature['properties']) 
                            point_x = vkm_feature['properties']['x']
                            point_y = vkm_feature['properties']['y']
                            tie = str(vkm_feature['properties']['tie'])
                            ajorata = str(vkm_feature['properties']['ajorata'])
                            osa = str(vkm_feature['properties']['osa'])
                            etaisyys = str(vkm_feature['properties']['etaisyys'])
                            hallinnollinen_luokka = str(vkm_feature['properties']['hallinnollinen_luokka'])
                            kuntanimi = str(vkm_feature['properties']['kuntanimi'])
                            katunimi = str(vkm_feature['properties']['katunimi'])
                            katunumero = str(vkm_feature['properties']['katunumero'])
                            elynimi = str(vkm_feature['properties']['elynimi'])
                            ualuenimi = str(vkm_feature['properties']['ualuenimi'])
                            maakuntanimi = str(vkm_feature['properties']['maakuntanimi'])
                            #maantien_nimi = str(vkm_feature['properties']['maantien_nimi'])

                            dlg.XlineEdit.setText(str(point_x))
                            dlg.YlineEdit.setText(str(point_y))
                            dlg.TielineEdit.setText(tie)
                            dlg.AjoratalineEdit.setText(ajorata)
                            dlg.OsalineEdit.setText(osa)
                            dlg.EtaisyyslineEdit.setText(etaisyys)
                            dlg.HaLulineEdit.setText(hallinnollinen_luokka)
                            dlg.KuntanimilineEdit.setText(kuntanimi)
                            dlg.KatunimilineEdit.setText(katunimi)
                            dlg.KatunumerolineEdit.setText(katunumero)
                            dlg.ElynimilineEdit.setText(elynimi)
                            dlg.UaluenimilineEdit.setText(ualuenimi)
                            dlg.MaakuntanimilineEdit.setText(maakuntanimi)

                            road_address = f'{tie}/{ajorata}/{osa}/{etaisyys}'
                            
                        except:
                            point_x = vkm_feature['properties']['x']
                            point_y = vkm_feature['properties']['y']
                            tie = str(vkm_feature['properties']['tie'])
                            ajorata = str(vkm_feature['properties']['ajorata'])
                            osa = str(vkm_feature['properties']['osa'])
                            etaisyys = str(vkm_feature['properties']['etaisyys'])
                            hallinnollinen_luokka = str(vkm_feature['properties']['hallinnollinen_luokka'])
                            kuntanimi = str(vkm_feature['properties']['kuntanimi'])
                            #katunimi = str(vkm_feature['properties']['katunimi'])
                            #katunumero = str(vkm_feature['properties']['katunumero'])
                            elynimi = str(vkm_feature['properties']['elynimi'])
                            ualuenimi = str(vkm_feature['properties']['ualuenimi'])
                            maakuntanimi = str(vkm_feature['properties']['maakuntanimi'])
                            #maantien_nimi = str(vkm_feature['properties']['maantien_nimi'])

                            dlg.XlineEdit.setText(str(point_x))
                            dlg.YlineEdit.setText(str(point_y))
                            dlg.TielineEdit.setText(tie)
                            dlg.AjoratalineEdit.setText(ajorata)
                            dlg.OsalineEdit.setText(osa)
                            dlg.EtaisyyslineEdit.setText(etaisyys)
                            dlg.HaLulineEdit.setText(hallinnollinen_luokka)
                            dlg.KuntanimilineEdit.setText(kuntanimi)
                            #dlg.KatunimilineEdit.setText(katunimi)
                            #dlg.KatunumerolineEdit.setText(katunumero)
                            dlg.ElynimilineEdit.setText(elynimi)
                            dlg.UaluenimilineEdit.setText(ualuenimi)
                            dlg.MaakuntanimilineEdit.setText(maakuntanimi)
                            
                            road_address = f'{tie}/{ajorata}/{osa}/{etaisyys}'

                    if vkm_error == True:
                        self.error_popup(road_address=road_address)

                    else:
                        self.add_point(road_address=road_address, point_x=point_x, point_y=point_y)
                        

            except AttributeError:
                pass

        
        canvas = self.iface.mapCanvas()
        pointTool = QgsMapToolEmitPoint(canvas)
        pointTool.canvasClicked.connect(display_popup)
        canvas.setMapTool(pointTool)
        display_popup(pointTool)
        dlg.show()
        dlg.exec_()
        dlg.SuljeButton.clicked.connect(self.close_popup)
        
    
    #def road_part(self):
    #    
    #    pass
        

    def two_points(self):

        if self.first_start == True:
            self.first_start = False
        self.two_points_dlg = ShowCoordinates_dialog()
        self.two_points_dlg.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)

        self.ajoradat_dlg = Ajoradat_dialog()
        self.ajoradat_dlg.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)

        #setting values that functions A and B need to use
        QgsProject.instance().setCrs(self.my_crs)
        self.canvas = self.iface.mapCanvas()

        


        def display_point_A(pointTool_A):

            #variables for display_point_B
            self.tie_A = 0
            self.osa_A = 0
            self.etaisyys_A = 0
            self.ajoradat_dlg.Ajorata0lineEdit.clear()
            self.ajoradat_dlg.Ajorata1lineEdit.clear()
            self.ajoradat_dlg.Ajorata2lineEdit.clear()


            try:

                #click on canvas returns coordinates
                print('Point A')
                #print(pointTool_A.x(), pointTool_A.y())
                point_x = str(pointTool_A.x())
                point_y = str(pointTool_A.y())
                self.two_points_dlg.CoordLineEdit.setText(f'{point_x}, {point_y}')

                #get new coordinates and address from VKM
                vkm_url='https://avoinapi.vaylapilvi.fi/viitekehysmuunnin/'

                try:
                    road_address, vkm_error, point_x, point_y, tie_A, osa_A, etaisyys_A = self.vkm_request_road_address(vkm_url=vkm_url, point_x=point_x, point_y=point_y, display_point='A')
                except:
                    road_address, vkm_error = self.vkm_request_road_address(vkm_url=vkm_url, point_x=point_x, point_y=point_y, display_point='A ')

                if vkm_error == True:
                    self.error_popup(road_address=road_address)
                    return
                
                else:
                    #dlg.AddrLineEdit.setText(road_address)
                    self.add_point(road_address=road_address, point_x=point_x, point_y=point_y)
                    
                    #adding an annotation with road address to the latest point
                    self.add_annotation(road_address=road_address, point_x=point_x, point_y=point_y)
                    
                    self.tie_A = tie_A
                    self.osa_A = osa_A
                    self.etaisyys_A = etaisyys_A
                
                    print(f'Tie A {self.tie_A}')

                    #connecting canvas to pointTool B
                    self.canvas.setMapTool(pointTool_B)        
            except AttributeError:
                pass


        def display_point_B(pointTool_B):

            try:

                #click on canvas returns coordinates
                print('Point B')
                #print(pointTool_B.x(), pointTool_B.y())
                point_x = str(pointTool_B.x())
                point_y = str(pointTool_B.y())
                self.two_points_dlg.CoordLineEdit.setText(f'{point_x}, {point_y}')

                #get new coordinates and address from VKM
                vkm_url='https://avoinapi.vaylapilvi.fi/viitekehysmuunnin/'

                try:
                    road_address, vkm_error, point_x_B, point_y_B, tie_B, osa_B, etaisyys_B = self.vkm_request_road_address(vkm_url=vkm_url, point_x=point_x, point_y=point_y, display_point='B')
                except:    
                    road_address, vkm_error = self.vkm_request_road_address(vkm_url=vkm_url, point_x=point_x, point_y=point_y, display_point='B ')

                if vkm_error == True:
                    self.canvas.setMapTool(pointTool_A)
                    self.error_popup(road_address=road_address)
                    return
                
                elif tie_B != self.tie_A:
                    self.canvas.setMapTool(pointTool_A)
                    self.error_popup('Alku- ja loppupisteen on oltava samalla tiellä')
                    return
                
                else:
                    #dlg.AddrLineEdit.setText(road_address)
                    self.add_point(road_address=road_address, point_x=point_x_B, point_y=point_y_B)
                    
                    #adding an annotation with road address to the latest point
                    self.add_annotation(road_address=road_address, point_x=point_x_B, point_y=point_y_B)

                    
                    #getting road address and calculating the distance of roadway(s) between points A and B
                    

                    try:
                        polyline_dict, pituus_dict = self.vkm_request_geometry(vkm_url, self.tie_A, self.osa_A, self.etaisyys_A, tie_B, osa_B, etaisyys_B)

                        #print(f'polyline_coordinates {polyline_coordinates}')
                        #print(f'pituus {pituus}')

                        #if error_message != None:
                        #    self.error_popup(road_address=error_message)
                        #    raise Exception

                        #print(polyline_dict)

                        for ajorata, coordinates in polyline_dict.items():
                            print(f'{ajorata} - {coordinates}')
                            print('\n')
                            
                            #road_address_split = road_address.split('/')
                            #road_address_split[1] = ajorata
                            #road_address = '/'.join(road_address_split)
                            
                            for ajorata_pituus, pituus in pituus_dict.items():
                                if ajorata_pituus == ajorata:
                                    mitattu_pituus = pituus
                                    break
                            roadway = f'A {self.tie_A}/{ajorata}/{self.osa_A}/{self.etaisyys_A} - B {tie_B}/{ajorata}/{osa_B}/{etaisyys_B} pituus: {mitattu_pituus}'

                            for linestring in coordinates:
                                xy_points = self.convert_coordinates_to_XY(linestring)
                                if ajorata == '0':
                                    self.add_polyline(xy_points, roadway, color='green')
                                elif ajorata == '1':
                                    self.add_polyline(xy_points, roadway, color='yellow')
                                elif ajorata == '2':
                                    self.add_polyline(xy_points, roadway, color='blue')

                            if ajorata == '0':
                                self.ajoradat_dlg.Ajorata0lineEdit.clear()
                                self.ajoradat_dlg.Ajorata0lineEdit.setText(roadway)
                            elif ajorata == '1':
                                self.ajoradat_dlg.Ajorata1lineEdit.clear()
                                self.ajoradat_dlg.Ajorata1lineEdit.setText(roadway)
                            elif ajorata == '2':
                                self.ajoradat_dlg.Ajorata2lineEdit.clear()
                                self.ajoradat_dlg.Ajorata2lineEdit.setText(roadway)
                        
                        #showing all the roadways
                        self.ajoradat_dlg.show()
                        result = self.ajoradat_dlg.exec_()
                        #connecting canvas back to pointTool A
                        self.canvas.setMapTool(pointTool_A)

                        if result:
                            self.canvas.setMapTool(pointTool_A)
                            pass

                    except:
                        self.canvas.setMapTool(pointTool_A)
                        return

            except AttributeError:
                    pass


    
        pointTool_A = QgsMapToolEmitPoint(self.canvas)
        pointTool_A.canvasClicked.connect(display_point_A)
        self.canvas.setMapTool(pointTool_A)
        display_point_A(pointTool_A)

        pointTool_B = QgsMapToolEmitPoint(self.canvas)
        pointTool_B.canvasClicked.connect(display_point_B)
        display_point_B(pointTool_B)
        
        
        #pointTool_B = QgsMapToolEmitPoint(canvas)
        #pointTool_B.canvasClicked.connect(lambda: display_point_B(pointTool_B, point_x_A, point_y_A, tie_A))

        #try:
        #    point_x_A, point_y_A, tie_A = display_point_A(pointTool_A)
        #    print(f'point_y_A = {point_y_A} \n tie_A = {tie_A}')
        #    display_point_B(pointTool_B, point_x_A, point_y_A, tie_A)
        #except:
        #    display_point_A(pointTool_A)

        #self.display_point_B(pointTool)

        self.two_points_dlg.show()
        # Run the dialog event loop
        result = self.two_points_dlg.exec_()

        
        # See if OK was pressed
        if result:
            
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass


# ---------------- EXTRA FUNCTIONS ---------------------- 

    def vkm_request_road_address(self, vkm_url, point_x, point_y, display_point='', palautus_arvot='1,2'):
        response = get(vkm_url + f'muunna?x={point_x}&y={point_y}&palautusarvot={palautus_arvot}&vaylan_luonne=0')

        while response.status_code !=200: #retry
            logging.info('retrying')
            response = get(vkm_url + f'muunna?x={point_x}&y={point_y}&palautusarvot={palautus_arvot}&vaylan_luonne=0')

        vkm_error = False
        vkm_data = json.loads(response.content)
        for vkm_feature in vkm_data['features']:

            if 'virheet' in vkm_feature['properties']:
                road_address = display_point + vkm_feature['properties']['virheet']
                vkm_error = True
            
            else:
                try:
                    #getting road coordinates and road address that are nearest to the mouse click
                    #print(vkm_feature['properties']) 
                    point_x = vkm_feature['properties']['x']
                    point_y = vkm_feature['properties']['y']
                    tie = str(vkm_feature['properties']['tie'])
                    ajorata = str(vkm_feature['properties']['ajorata'])
                    osa = str(vkm_feature['properties']['osa'])
                    etaisyys = str(vkm_feature['properties']['etaisyys'])
                    
                    road_address = f'{display_point} {tie}/{ajorata}/{osa}/{etaisyys}'

                except:
                    #nearest address is a street -> no road address
                    #print(vkm_feature['properties'])
                    point_x = vkm_feature['properties']['x']
                    point_y = vkm_feature['properties']['y']

                    road_address = f'Ei tieosoitetta'
        #print(road_address)
        if vkm_error == True:
            return road_address, vkm_error
        else:
            return road_address, vkm_error, point_x, point_y, tie, osa, etaisyys

    
    def add_point(self, road_address, point_x, point_y):
        point_layer = QgsVectorLayer('Point', f'Piste ({road_address})', 'memory')
        pr = point_layer.dataProvider()
        pr.addAttributes([QgsField("ID", QVariant.String)])
        point_layer.updateFields()
        feature = QgsFeature()
        feature.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(point_x, point_y)))
        feature.setAttributes(['1'])
        
        #each point is added as a separate layer
        pr.addFeature(feature)
        point_layer.updateExtents()
        point_layer.setCrs(self.my_crs)

        #renderer = point_layer.renderer()
        #renderer.symbol().setWidth(0.5)
        #point_layer.triggerRepaint()

        QgsProject.instance().addMapLayer(point_layer)


    def add_annotation(self, road_address, point_x, point_y):
        layer = self.iface.activeLayer()

        annot = QgsTextAnnotation()
        annot_length = len(road_address) * 2

        annot.setFrameSizeMm(QSizeF(annot_length, 6))
        annot.setMapLayer(layer)
        annot.setFrameOffsetFromReferencePointMm(QPoint(10, 15))
        annot.setDocument(QTextDocument(road_address))

        # X and Y are defined previously
        annot.setMapPositionCrs(QgsCoordinateReferenceSystem(layer.crs()))
        annot.setMapPosition(QgsPointXY(point_x, point_y))

        QgsProject.instance().annotationManager().addAnnotation(annot)

    
    def add_polyline(self, xy_points, roadway, color):
        if color == 'green':
            polyline_color = QColor(0,255,0)
        elif color == 'yellow':
            polyline_color = QColor(255,165,0)
        elif color == 'blue':
            polyline_color = QColor(0,0,255)

        polyline_layer = QgsVectorLayer('LineString?crs=3067&field=id:integer&index=yes', f'Ajorata ({roadway})', 'memory')
        pr = polyline_layer.dataProvider()
        pr.addAttributes([QgsField("ID", QVariant.String)])
        polyline_ft = QgsFeature()
        
        polyline_ft.setGeometry(QgsGeometry.fromPolylineXY(xy_points))
        polyline_ft.setAttributes(['1'])
#
        pr.addFeature(polyline_ft)
        polyline_layer.updateExtents()
        polyline_layer.setCrs(self.my_crs)

        renderer = polyline_layer.renderer()
        renderer.symbol().setWidth(0.6)
        renderer.symbol().setColor(polyline_color)
        polyline_layer.triggerRepaint()

        QgsProject.instance().addMapLayer(polyline_layer)

    
    def convert_coordinates_to_XY(self, linestring):
        xy_points = []
        if len(linestring) < 2:
            xy_points.append(QgsPointXY(linestring[0], linestring[1]))
        for coordinates in linestring:
            xy_points.append(QgsPointXY(coordinates[0], coordinates[1]))
        return xy_points

        
    def close_popup(self):
        dlg = PopUp_dialog
        dlg.close()

    
    def error_popup(self, road_address):
            self.iface.messageBar().pushMessage(
            f'{road_address}',
            level=1, duration=10)

    
    def vkm_request_geometry(self, vkm_url, tie_A, osa_A, etaisyys_A, tie_B, osa_B, etaisyys_B, display_point='', palautus_arvot='1,2,5'):

        response = get(vkm_url + f'muunna?tie={tie_A}&osa={osa_A}&etaisyys={etaisyys_A}&tie_loppu={tie_B}&osa_loppu={osa_B}&etaisyys_loppu={etaisyys_B}&vaylan_luonne=0&valihaku=true&palautusarvot={palautus_arvot}')
        polyline_dict = {}
        pituus_dict = {}
        
        while response.status_code !=200: #retry
            logging.info('retrying')
            response = get(vkm_url + f'muunna?tie={tie_A}&osa={osa_A}&etaisyys={etaisyys_A}&tie_loppu={tie_B}&osa_loppu={osa_B}&etaisyys_loppu={etaisyys_B}&vaylan_luonne=0&valihaku=true&palautusarvot={palautus_arvot}')
        vkm_data = json.loads(response.content)
        
        error_message = None

        for vkm_feature in vkm_data['features']:
            #print(vkm_feature)

            if 'virheet' in vkm_feature['properties']:
                error_message = display_point + vkm_feature['properties']['virheet']
                self.error_popup(error_message)
                return

            else:
                ajorata = str(vkm_feature['properties']['ajorata'])
                
                #check if a key already exist and append a linestring to it
                try:
                    for linestring in vkm_feature['geometry']['coordinates']:
                        polyline_dict[ajorata].append(linestring)
                except:
                    polyline_dict[ajorata] = []
                    for linestring in vkm_feature['geometry']['coordinates']:
                        polyline_dict[ajorata].append(linestring)

                #print(vkm_feature['properties'])
                try:
                    vkm_pituus = str(vkm_feature['properties']['mitattu_pituus'])
                except:
                    vkm_pituus = abs(vkm_feature['properties']['etaisyys'] - vkm_feature['properties']['etaisyys_loppu'])
                pituus_dict[ajorata] = str(vkm_pituus)
                
        return polyline_dict, pituus_dict

                